#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-flatbuffers
Version  : 1.2.0
Release  : 2
URL      : https://github.com/google/flatbuffers/archive/v1.2.0.tar.gz
Source0  : https://github.com/google/flatbuffers/archive/v1.2.0.tar.gz
Source1  : https://repo1.maven.org/maven2/com/vlkan/flatbuffers/1.2.0-3f79e055/flatbuffers-1.2.0-3f79e055.jar
Source2  : https://repo1.maven.org/maven2/com/vlkan/flatbuffers/1.2.0-3f79e055/flatbuffers-1.2.0-3f79e055.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-flatbuffers-data = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-golang

%description
FlatBuffers Version 1.1.0
# Welcome to FlatBuffers!
## Build Status
- Travis: [![Build Status](https://travis-ci.org/google/flatbuffers.svg?branch=master)](https://travis-ci.org/google/flatbuffers)

%package data
Summary: data components for the mvn-flatbuffers package.
Group: Data

%description data
data components for the mvn-flatbuffers package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vlkan/flatbuffers/1.2.0-3f79e055
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/vlkan/flatbuffers/1.2.0-3f79e055/flatbuffers-1.2.0-3f79e055.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vlkan/flatbuffers/1.2.0-3f79e055
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/vlkan/flatbuffers/1.2.0-3f79e055/flatbuffers-1.2.0-3f79e055.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/vlkan/flatbuffers/1.2.0-3f79e055/flatbuffers-1.2.0-3f79e055.jar
/usr/share/java/.m2/repository/com/vlkan/flatbuffers/1.2.0-3f79e055/flatbuffers-1.2.0-3f79e055.pom
